site_name: IHC - UVa

theme:
    name: material
    language: pt
    logo: https://cdn.discordapp.com/attachments/752588141298450563/752604546303524934/uva.png
    favicon: https://www.codepuppet.com/wp-content/uploads/2013/10/uva.png

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/Interacao-Humano-Computador/2020.1-UVaJudge

nav:
    - Sobre: index.md
    - Planejamento do Projeto:
        - Porque UVa?: entrega_1/porque_uva.md
        - Cronograma de atividades: entrega_1/cronograma_atividades.md
        - Ferramentas: entrega_1/ferramentas.md
        - Sites avaliados: 
            - UVa Online Judge:
                - Planejamento da avaliação: entrega_1/planejamentos_individuais/planejamento_uva.md
                - Avaliação: entrega_1/avaliacoes_individuais/avaliacao_uva.md
            - MangaLivre:
                - Planejamento da avaliação: entrega_1/planejamentos_individuais/planejamento_mangalivre.md
                - Avaliação: entrega_1/avaliacoes_individuais/avaliacao_mangalivre.md
            - Poupa Tempo SP:
                - Planejamento da avaliação: entrega_1/planejamentos_individuais/planejamento_poupatemposp.md
                - Avaliação: entrega_1/avaliacoes_individuais/avaliacao_poupatemposp.md
        - Processo de Design: entrega_1/processo_design.md
        - Análise do Perfil de Usuário:
            - Perfil de usuário: entrega_2/perfil_usuario.md
            - Questionário: entrega_2/questionario.md
            - Entrevista: entrega_2/entrevista.md
        - Personas: entrega_2/personas.md
        - Análise de tarefas: entrega_2/analise_tarefas.md
        - Princípios e diretrizes do projeto: entrega_3/principios_gerais.md
    - Atas das reuniões:
        - Reunião 1: atas/reuniao_1.md
        - Reunião 2: atas/reuniao_2.md
        - Reunião 3: atas/reuniao_3.md
        - Reunião 4: atas/reuniao_4.md
        - Reunião 5: atas/reuniao_5.md
        - Reunião 6: atas/reuniao_6.md
        - Reunião 7: atas/reuniao_7.md
        - Reunião 8: atas/reuniao_8.md
    - Apresentações:
        - Apresentação 1: apresentacoes/apresentacao_1.md
        - Apresentação 2: apresentacoes/apresentacao_2.md
